# Dockerfile示例

# 第一行必须指定基于的镜像基础
FROM nginx

# 维护者信息
MAINTAINER XXX XXX@qq.com

# 镜像的操作指令
RUN echo '<h1>Hello, Docker!</h1>' > /usr/share/nginx/html/index.html

# 容器启动时执行指令
# ！！这个示例功能比较简单，不需要在容器启动是执行指令